apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  tasks:
    - name: say-hello
      taskSpec:
        steps:
          - name: echo
            image: alpine
            command:
              - echo
            args:
              - "hello, world"
    - name: enterprise-contract-check
      taskRef:
        name: ec-task
        bundle: quay.io/enterprise-contract/ec-task:latest
      params:
        - name: IMAGE_REF
          value: your-image-reference
        - name: POLICY_CONFIGURATION
          value: always-pass-policy
        - name: STRICT
          value: "false"
