apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  tasks:
    - name: say-hello
      taskSpec:
        steps:
          - name: echo
            image: alpine
            command:
              - echo
            args:
              - "hello, world"