apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
  name: test-rpa
  namespace: sbudhwar-1-tenant
spec:
  applications:
    - new-test-app
  origin: sbudhwar-1-tenant
  pipeline: 
    pipelineRef:
      resolver: 'git'
      params:
        - name: 'url'
          value: 'https://github.com/sahil143/pipeline-examples'
        - name: 'revision'
          value: 'main'
        - name: 'pathInRepo'
          value: 'release.yaml'
  policy: always-pass-policy